language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "simozmp"
    token:
      secure: "mqXN/DCltlleLRYpV8eEWhareceiszLE5btNJ/DG+PSpJIau4BU8Y3bSxThH2X0nZmYLyHdgBiFehFs6dv+9XRXpMAGXOc8BLpl+scXu1lrsTgjDevXn6vIKcybDfEgnLasi4sghcuixNaE+62RhkvnNXkke78IfpUzZsnMWX4eRq2AgwIjLMy+18JNz04PcGf5w4p7CE+vbhG0XQy9RO1DoQim1m/HAYQxqPvPlTP5ZO3cf1452QJo84+p1lsdQL/x/zAx9qUL53dm09NExUHUxbwf36MjY9TLCiNwMFeoUKOdLXB+4NM/nEjije2YHpmr8xjugJTT3abSXcujFwZHvMZ3+G+S6kC2+UH9EIvHgLMrVFHKb1TFd/sA/FCixE85pyUqcfV0m1MiVP29WEo+I/Af39x/L2dtJDzb1DpVEd+Gz/sAV+xbcxydkGIsxPjbDhW6Qd63ojOLXLJ/2jh1SqwnNDcw+kHdgU24vvLJcq3mtJZx3mTrRSqpPCwrhNxnu98kct/66jNd4yVwkUYLHa5Uw4vrGbXyorz22pwePeyEb58cxWWBrnDbllKAPIgQq6P2c9bTHhGhD2ZgL0IjxyhANwXqVOxKZhvMpzM9v4ytw6c9/yWCJ5fGoYlJq8gcAQJLJ1JKYqGlcL49sW1o35tesf+0iHCOPpi0dTwU="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ant build
  - sonar-scanner -X
